### ISSUE TITLE
Refactor drawer

### ISSUE THREAD

**Issue by chronark** [perfolio/perfolio#534]
It should take a size argument like 
```typescript
type Breakpoint = "" | "xs:" | "sm:" | "md:" | "lg:" | "xl:" | "2xl:"
type Ratio = "full" | "1/2" | "1/3" ...
type Size = `${Breakpoint}${Ratio}`
```

that way we can set dynamic breakpoint sizes

**Comment by chronark** [comment]
@SaitaoGit

**Comment by SaitaoGit** [comment]
@chronark Do we really need the "Breakpoint" part? Should'nt it be enough to use something like:
`type Size = "xs" |  "sm" | "md"  ...
 type Ratio = "full" | "1/2" | "1/3" ...
`

**Comment by chronark** [comment]
could be useful, but we could also add that only if we need it later
