### ISSUE TITLE
"Go to dashboard" turns into client side error (See attachement for details)

### ISSUE THREAD

**Issue by Meisterlu** [perfolio/perfolio#546]
When clicking on own dashboard following error are shown.

![image](https://user-images.githubusercontent.com/55478918/151170835-12898bb7-a288-46f2-818a-4668112d6867.png)

**Comment by madsjordt** [comment]
Hab's gerade auch nochmal probiert. Bekomme den Error auch. Habe mich schon gefreut, weil es erst geladen hat :D
